# Validating measures

In [1]:
import pandas as pd
import numpy as np
import pickle as pkl
import matplotlib.pyplot as plt
import time

### Data Directory

In [2]:
INPUT_DIR = '../data/interim/'
OUTPUT_DIR = '../data/processed/'

### Reading predicted file

In [3]:
ip_file = INPUT_DIR + 'fd002_dbscan_results_5000_0.001.csv'
df_pred = pd.read_csv(ip_file, sep=',')

In [4]:
df_pred.head()

,setting1,setting2,setting3,meas01,meas02,meas03,meas04,meas05,meas06,meas07,...,meas13,meas14,meas15,meas16,meas17,meas20,meas21,unit,time_cycles,labels
0,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,21.61,554.36,...,2388.02,8138.62,8.4195,0.03,392,39.06,23.4190,1,1,0
1,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,21.61,553.75,...,2388.07,8131.49,8.4318,0.03,392,39.00,23.4236,1,2,0
2,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,21.61,554.26,...,2388.03,8133.23,8.4178,0.03,390,38.95,23.3442,1,3,0
3,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,21.61,554.45,...,2388.08,8133.83,8.3682,0.03,392,38.88,23.3739,1,4,0
4,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,21.61,554.00,...,2388.04,8133.80,8.4294,0.03,393,38.90,23.4044,1,5,0

In [5]:
# Make everything in labels column into 0 or -1
df_pred['labels'] = df_pred['labels'].apply(lambda x: 0 if x >= 0 else -1)

### Generating Ground Truth with heuristics

In [6]:
timecycles_for_failure = 10

In [7]:
df_pred['ground_truth'] = 0

In [8]:
df_pred.head()

,setting1,setting2,setting3,meas01,meas02,meas03,meas04,meas05,meas06,meas07,...,meas14,meas15,meas16,meas17,meas20,meas21,unit,time_cycles,labels,ground_truth
0,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,21.61,554.36,...,8138.62,8.4195,0.03,392,39.06,23.4190,1,1,0,0
1,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,21.61,553.75,...,8131.49,8.4318,0.03,392,39.00,23.4236,1,2,0,0
2,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,21.61,554.26,...,8133.23,8.4178,0.03,390,38.95,23.3442,1,3,0,0
3,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,21.61,554.45,...,8133.83,8.3682,0.03,392,38.88,23.3739,1,4,0,0
4,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,21.61,554.00,...,8133.80,8.4294,0.03,393,38.90,23.4044,1,5,0,0

In [9]:
units = np.unique(df_pred['unit'])

In [10]:
df_pred.loc[df_pred['unit'] == -1]

Empty DataFrame
Columns: [setting1, setting2, setting3, meas01, meas02, meas03, meas04, meas05, meas06, meas07, meas08, meas09, meas10, meas11, meas12, meas13, meas14, meas15, meas16, meas17, meas20, meas21, unit, time_cycles, labels, ground_truth]
Index: []

[0 rows x 26 columns]

In [11]:
# Assign outliers for the last 'n' time cycles for each of the unit

units = np.unique(df_pred['unit'])
# print('Number of unique units:', len(units))
for current_unit in units:
    df_sub = df_pred.loc[df_pred['unit'] == current_unit]
    max_timecycle = max(df_sub['time_cycles'])    
    outlier_time_threshold = max_timecycle - timecycles_for_failure
    
    # print('Unit=', current_unit, 'outlier threshold', outlier_time_threshold)
    
    df_pred['ground_truth'].loc[(df_pred['unit'] == current_unit) & (df_pred['time_cycles'] > outlier_time_threshold)] = -1

/Users/talat/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [12]:
print(df_pred[['unit', 'time_cycles', 'labels', 'ground_truth']].loc[df_pred['unit'] == 1])

     unit  time_cycles  labels  ground_truth
0       1            1       0             0
1       1            2       0             0
2       1            3       0             0
3       1            4       0             0
4       1            5       0             0
5       1            6       0             0
6       1            7       0             0
7       1            8       0             0
8       1            9       0             0
9       1           10       0             0
10      1           11       0             0
11      1           12       0             0
12      1           13       0             0
13      1           14       0             0
14      1           15       0             0
15      1           16       0             0
16      1           17       0             0
17      1           18       0             0
18      1           19       0             0
19      1           20       0             0
20      1           21       0             0
21      1           22       0             0
22      1           23       0             0
23      1           24       0             0
24      1           25       0             0
25      1           26       0             0
26      1           27       0             0
27      1           28       0             0
28      1           29       0             0
29      1           30       0             0
..    ...          ...     ...           ...
162     1          163       0             0
163     1          164       0             0
164     1          165       0             0
165     1          166       0             0
166     1          167       0             0
167     1          168       0             0
168     1          169       0             0
169     1          170       0             0
170     1          171       0             0
171     1          172       0             0
172     1          173       0             0
173     1          174       0             0
174     1          175       0             0
175     1          176       0             0
176     1          177       0             0
177     1          178      -1             0
178     1          179       0             0
179     1          180       0             0
180     1          181       0             0
181     1          182       0             0
182     1          183       0            -1
183     1          184      -1            -1
184     1          185      -1            -1
185     1          186       0            -1
186     1          187       0            -1
187     1          188       0            -1
188     1          189       0            -1
189     1          190      -1            -1
190     1          191      -1            -1
191     1          192      -1            -1

[192 rows x 4 columns]

In [13]:
print('Number of outliers in the predicted values', len(df_pred.loc[df_pred['labels'] == -1]))
print('Number of outliers in the ground truth', len(df_pred.loc[df_pred['ground_truth'] == -1]))

Number of outliers in the predicted values 1015
Number of outliers in the ground truth 1000

In [14]:
# Copy into a new dataframe with only the required columns
df_scoring = df_pred[['unit', 'time_cycles', 'labels', 'ground_truth']].copy()

In [15]:
# tp = 0
# fp = 1
# fn = 2
# tn = 3

def gen_vals(ground_truth, pred_label, pos_label, neg_label):
    if (ground_truth == pos_label) & (pred_label == pos_label):
        return 0
    elif (ground_truth == neg_label) & (pred_label == pos_label):
        return 1
    elif (ground_truth == pos_label) & (pred_label == neg_label):
        return 2
    elif (ground_truth == neg_label) & (pred_label == neg_label):
        return 3

### Find out the f-measure

In [16]:
pos_label = -1
neg_label = 0

df_scoring['pos'] = -1

df_scoring['pos'] = df_scoring.apply(lambda x: gen_vals(x['ground_truth'], x['labels'], pos_label, neg_label), axis=1)

In [17]:
from collections import Counter
counter = Counter(df_scoring['pos'])

print(counter)

accuracy = (counter[0] + counter[3]) / (counter[0] + counter[1] + counter[2] + counter[3])
print('Accuracy = ', accuracy)

precision = counter[0] / (counter[0] + counter[1])
print('Precision = ', precision)

recall = counter[0] / (counter[0] + counter[2])
print('Recall = ', recall)

f1_score = 2 * (precision * recall) / (precision + recall)
print('F1 score: ', f1_score)

Counter({3: 19166, 0: 550, 1: 465, 2: 450})
Accuracy =  0.9556492656681692
Precision =  0.541871921182266
Recall =  0.55
F1 score:  0.5459057071960298

# Making it into a function

In [18]:
def find_eval_metrics(df_pred, timecycles_for_failure):

    # Make everything in labels column into 0 or -1
    df_pred['labels'] = df_pred['labels'].apply(lambda x: 0 if x >= 0 else -1)
    
    df_pred['ground_truth'] = 0
    
    # Assign outliers for the last 'n' time cycles for each of the unit
    units = np.unique(df_pred['unit'])
    # print('Number of unique units:', len(units))
    for current_unit in units:
        df_sub = df_pred.loc[df_pred['unit'] == current_unit]
        max_timecycle = max(df_sub['time_cycles'])    
        outlier_time_threshold = max_timecycle - timecycles_for_failure

        # print('Unit=', current_unit, 'outlier threshold', outlier_time_threshold)

        df_pred['ground_truth'].loc[(df_pred['unit'] == current_unit) & (df_pred['time_cycles'] > outlier_time_threshold)] = -1
        
    # Copy into a new dataframe with only the required columns
    df_scoring = df_pred[['unit', 'time_cycles', 'labels', 'ground_truth']].copy()
    
    pos_label = -1
    neg_label = 0

    df_scoring['pos'] = -1
    df_scoring['pos'] = df_scoring.apply(lambda x: gen_vals(x['ground_truth'], x['labels'], pos_label, neg_label), axis=1)
    
    counter = Counter(df_scoring['pos'])

    accuracy = (counter[0] + counter[3]) / (counter[0] + counter[1] + counter[2] + counter[3])
    # print('Accuracy = ', accuracy)
    precision = counter[0] / (counter[0] + counter[1])
    # print('Precision = ', precision)
    recall = counter[0] / (counter[0] + counter[2])
    # print('Recall = ', recall)
    f1_score = 2 * (precision * recall) / (precision + recall)
    # print('F1 score: ', f1_score)
    
    return accuracy, precision, recall, f1_score

In [19]:
import warnings
warnings.filterwarnings("ignore")

max_timecycles_for_failure = 40

print('| timecycles_for_failure|', 'accuracy', '|', 'precision', '|', 'recall', '|', 'f1_score', '|')
print('|--|--|--|--|--|')

for i in range(1, max_timecycles_for_failure+1):
    accuracy, precision, recall, f1_score = find_eval_metrics(df_pred, i)
    print('|', i, '|', accuracy, '|', precision, '|', recall, '|', f1_score, '|')

| timecycles_for_failure| accuracy | precision | recall | f1_score |
|--|--|--|--|--|
| 1 | 0.9533226697687945 | 0.0748768472906404 | 0.76 | 0.13632286995515697 |
| 2 | 0.9546798507100964 | 0.13793103448275862 | 0.7 | 0.23045267489711935 |
| 3 | 0.9556492656681692 | 0.19704433497536947 | 0.6666666666666666 | 0.30418250950570347 |
| 4 | 0.9564247976346275 | 0.2541871921182266 | 0.645 | 0.3646643109540636 |
| 5 | 0.9574911540885076 | 0.3142857142857143 | 0.638 | 0.4211221122112211 |
| 6 | 0.9574911540885076 | 0.36354679802955664 | 0.615 | 0.4569659442724458 |
| 7 | 0.9573942125927003 | 0.41182266009852214 | 0.5971428571428572 | 0.48746355685131193 |
| 8 | 0.9572003296010857 | 0.45911330049261084 | 0.5825 | 0.5134986225895317 |
| 9 | 0.9566186806262421 | 0.5024630541871922 | 0.5666666666666667 | 0.5326370757180157 |
| 10 | 0.9556492656681692 | 0.541871921182266 | 0.55 | 0.5459057071960298 |
| 11 | 0.9546798507100964 | 0.5812807881773399 | 0.5363636363636364 | 0.5579196217494089 |
| 12 | 0.9532257282729872 | 0.6157635467980296 | 0.5208333333333334 | 0.5643340857787812 |
| 13 | 0.9519654888274927 | 0.6522167487684729 | 0.5092307692307693 | 0.5719222462203025 |
| 14 | 0.9502205419029616 | 0.683743842364532 | 0.4957142857142857 | 0.5747412008281574 |
| 15 | 0.9487664194658524 | 0.7182266009852217 | 0.486 | 0.5797216699801192 |
| 16 | 0.9465367650622849 | 0.7448275862068966 | 0.4725 | 0.5782026768642448 |
| 17 | 0.9441132276671029 | 0.7694581280788177 | 0.45941176470588235 | 0.5753222836095764 |
| 18 | 0.9421743977509573 | 0.7990147783251231 | 0.45055555555555554 | 0.5761989342806394 |
| 19 | 0.9395569773641608 | 0.8216748768472907 | 0.43894736842105264 | 0.57221269296741 |
| 20 | 0.9362609665067132 | 0.8374384236453202 | 0.425 | 0.5638474295190713 |
| 21 | 0.9332557801366875 | 0.8561576354679803 | 0.4138095238095238 | 0.5579454253611557 |
| 22 | 0.92995976927924 | 0.8719211822660099 | 0.4022727272727273 | 0.5505443234836703 |
| 23 | 0.9266637584217925 | 0.8876847290640394 | 0.3917391304347826 | 0.5435897435897435 |
| 24 | 0.9230769230769231 | 0.9004926108374385 | 0.38083333333333336 | 0.535285505124451 |
| 25 | 0.9194900877320537 | 0.9133004926108375 | 0.3708 | 0.5274537695590327 |
| 26 | 0.9157093693955698 | 0.9241379310344827 | 0.3607692307692308 | 0.5189488243430151 |
| 27 | 0.9118317095632785 | 0.9339901477832512 | 0.3511111111111111 | 0.5103633916554509 |
| 28 | 0.9076632252435655 | 0.9408866995073891 | 0.3410714285714286 | 0.5006553079947575 |
| 29 | 0.903688623915467 | 0.9497536945812808 | 0.33241379310344826 | 0.4924648786717752 |
| 30 | 0.8997140225873685 | 0.9586206896551724 | 0.3243333333333333 | 0.4846824408468244 |
| 31 | 0.8954485967718482 | 0.9645320197044335 | 0.3158064516129032 | 0.475820170109356 |
| 32 | 0.8909892879647133 | 0.9684729064039409 | 0.3071875 | 0.46642941874258603 |
| 33 | 0.886723862149193 | 0.9743842364532019 | 0.2996969696969697 | 0.4584009269988413 |
| 34 | 0.8821676118462508 | 0.9773399014778326 | 0.2917647058823529 | 0.4493771234428086 |
| 35 | 0.8777083030391158 | 0.9812807881773399 | 0.2845714285714286 | 0.4411960132890365 |
| 36 | 0.8730551112403664 | 0.9832512315270936 | 0.2772222222222222 | 0.4325027085590465 |
| 37 | 0.8684988609374242 | 0.9862068965517241 | 0.27054054054054055 | 0.42460233297985156 |
| 38 | 0.8640395521302894 | 0.9901477832512315 | 0.2644736842105263 | 0.41744548286604355 |
| 39 | 0.8593863603315399 | 0.9921182266009853 | 0.2582051282051282 | 0.40976602238046794 |
| 40 | 0.8548301100285978 | 0.9950738916256158 | 0.2525 | 0.40279162512462613 |